# Generated by Django 4.1.7 on 2023-04-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_enrollment_membershipplan_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='Reference',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='SelectTrainer',
        ),
    ]
