# Generated by Django 4.1.7 on 2023-04-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_bot_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bot',
            name='weight',
            field=models.FloatField(),
        ),
    ]
