# Generated by Django 4.1.7 on 2023-04-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_bot_height_alter_bot_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bot',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
    ]
