# Generated by Django 4.1.7 on 2023-05-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_alter_bot_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='birthday',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bot',
            name='height',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bot',
            name='weight',
            field=models.CharField(max_length=20),
        ),
    ]
